// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZn6QM1BP8U8O__rxM0ECVmge1AVgXInM',
    appId: '1:653940883523:web:96029c197602387e1114f6',
    messagingSenderId: '653940883523',
    projectId: 'roleplayingapp-ebfd4',
    authDomain: 'roleplayingapp-ebfd4.firebaseapp.com',
    databaseURL: 'https://roleplayingapp-ebfd4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'roleplayingapp-ebfd4.appspot.com',
    measurementId: 'G-17E0P9HC84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_z37U4chf25_L99NEIR74Ufqomoru2FM',
    appId: '1:653940883523:android:5de70b6eb9e111921114f6',
    messagingSenderId: '653940883523',
    projectId: 'roleplayingapp-ebfd4',
    databaseURL: 'https://roleplayingapp-ebfd4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'roleplayingapp-ebfd4.appspot.com',
  );
}
